apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-frontend
  labels:
    app: resume-builder-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-builder-frontend
  template:
    metadata:
      labels:
        app: resume-builder-frontend
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: frontend
        image: sainupopzienz/resume-ui:v1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://resume-builder-1717002635.us-east-1.elb.amazonaws.com/api"
---
apiVersion: v1
kind: Service
metadata:
  name: resume-builder-frontend-service
spec:
  type: NodePort
  selector:
    app: resume-builder-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30089
