apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVis0U1E0azc2UVl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01ESXdPVFEwTVRaYUZ3MHpOVEE1TXpBd09UUTVNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN6UjFiNFpiVEZGY0ZGd2FDdDQ1bnlGT0Y3dEhUZk1NUWhURVlJcnlBMXZIbFFMeUFQNWRVOVdQT0IKcDRhQnhiVW4wSDhXakJ0TlI5Mk5KcDl5RVluV3NmcFRoUHpRRm5aOWdVZm90OGFubVA5RVFFNVlaQXVZdjFRdgpFTjZCSFVYbVJMdFhjUFQyc01WbzduL0c5ME5GNTY2dXloZmtlblUwWnJ5akdtbWUxTHk2elVGVHN6T3I5cFZPCjNaSGd5a3FhTUFERWEyYXZURUV1eHZjNERXQnEvWW5NVWwweWJ5ZkpaZ2N6RnBBZ01yN1VFT2NHZWhXT1pUbnkKRTVDLzlZZ3Nsd2JHNEpOMmtDdlVSUVFHSWdnZXNnb1k3aVBBNksxZm1HZFR2MkRWbndUSDI0U2FhSTFpYkQwRgpmcVpQb2FOdS9lT0Vyc2ZIVkt2SlBNdExFcVJyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSMmcxZFMyVlV1dm5jQnVSbW45T21teG9Lc3NEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXZ3aWg3QlJ3cApKTTB4b1N1bE5BRklQNWxNeUpKNXpaVVNQcDhHQUtoSGNuZG1ER0J5dFk2ZmRvd2FLOHZmV0Uwd3o3L3lTZW4xCi80SUxaMHZwTXk3MHd6Y2N6NmJCejQ3US9qMXdNZk1qakgyYXQ1UjhzUGVtSzNBanA4K0htS3NNK2VFcjlSTW0KUkhwVXpRMXlCS1BGTElxWkxDSzlTczVlL1RyeGtnWWpuWW9GbWhYVmJtMkR0eDFBVTZ6SVRIQ2hMNVF3Ylo5ZgpkeEFOL28vbmFKb3Y0QmQ2RDdRSjJNQ0Jqc2NwUnpUbi9laVJPdmVoT0lzOFltaWxtOHl6OUF3am5DTTFMWXRYCis4dVhnejNjUlFmenZyWkRzT3RleEdpSXNFTGEzMlB4SXZ0Y2JVSjlwVWxMMS82V2pMYWZDQlQ3K21rUTdYTzYKQUg1REliN0tneGhUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://E8E266BE12FC6F3F8399A33D1D391772.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
    user: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
  name: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
current-context: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:379390614510:cluster/demo-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - demo-eks
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: kodekloud
