apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-frontend
  labels:
    app: resume-builder-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-builder-frontend
  template:
    metadata:
      labels:
        app: resume-builder-frontend
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: frontend
        image: sainupopzienz/resume-ui:v3  # Use v3 with correct API URL
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://54.152.194.43:30090/api"  # NodePort backend URL
